name: bolt receivers CI Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - name: bolt-koa
      run: cd packages/bolt-koa && npm test
    - name: bolt-fastify
      run: cd packages/bolt-fastify && npm test
